#ifndef WX_COMMANDS_S_H
#define WX_COMMANDS_S_H

UINT8 WXCmd_SDATA(UINT8 *ptr);
UINT8 WXCmd_SCON(UINT8 *ptr);
UINT8 WXCmd_SMGMT(UINT8 *ptr);
UINT8 WXCmd_SSEND(UINT8 *ptr);
UINT8 WXCmd_SFORM(UINT8 *ptr);
UINT8 WXCmd_SOPT1(UINT8 *ptr);
UINT8 WXCmd_SOPT2(UINT8 *ptr);
UINT8 WXCmd_SDNAME(UINT8 *ptr);

#endif
