/*
 * Copyright 2013, Broadcom Corporation
 * All Rights Reserved.
 *
 * This is UNPUBLISHED PROPRIETARY SOURCE CODE of Broadcom Corporation;
 * the contents of this file may not be disclosed to third parties, copied
 * or duplicated in any form, in whole or in part, without the prior
 * written permission of Broadcom Corporation.
 */

/**
 * @file
 * This provides the content (web pages) for the example web
 * server apps.
 *
 * It does not use a filesystem, all pages are generated by handler functions.
 * These functions simply copy data into the outgoing packet buffer.
 *
 */

#include "web_server.h"
#include "wwd_wifi.h"
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "wwd_constants.h"
#include "wwd_assert.h"

#include "internal/SDPCM.h"
#include "wwd_wlioctl.h"
#include "bootloader_app.h"
#include "watchdog.h"

/******************************************************
 *             Defines
 ******************************************************/
#define CIRCULAR_RESULT_BUFF_SIZE  (5)
#define SSID_FIELD_NAME            "ssid"
#define SECURITY_FIELD_NAME        "sec"
#define CHANNEL_FIELD_NAME         "chan"
#define BSSID_FIELD_NAME           "bssid"
#define PASSPHRASE_FIELD_NAME      "pwd"

/* Macros for comparing MAC addresses */
#define CMP_MAC( a, b )  (((a[0])==(b[0]))&& \
                          ((a[1])==(b[1]))&& \
                          ((a[2])==(b[2]))&& \
                          ((a[3])==(b[3]))&& \
                          ((a[4])==(b[4]))&& \
                          ((a[5])==(b[5])))

#define NULL_MAC( a )  (((a[0])==0)&& \
                        ((a[1])==0)&& \
                        ((a[2])==0)&& \
                        ((a[3])==0)&& \
                        ((a[4])==0)&& \
                        ((a[5])==0))

/******************************************************
 *             Structures
 ******************************************************/

typedef struct
{
    uint8_t scan_done;
    host_semaphore_type_t result_avail_sema;
    wiced_scan_result_t* result_buff;
} scan_cb_t;


/******************************************************
 *             Static Function Prototypes
 ******************************************************/

static int  process_send_file       ( void* socket, char * params, int params_len );
static int  process_update          ( void* socket, char * params, int params_len );
static int  process_del_app         ( void* socket, char * params, int params_len );
static void my_file_handler         ( void* data, int len);
/******************************************************
 *             Global variables
 ******************************************************/

/**
 * URL Handler List
 */
const url_list_elem_t url_list[] = {
                                     { "/",                   "text/html",   process_send_file, NULL },
                                     { "/index.html",         "text/html",   process_send_file, NULL },
                                     { "/update.html",        "text/html",   process_update,    my_file_handler },
                                     { "/delete_app.html",    "text/html",   process_del_app,   NULL },
                                     /* Add more pages here */
                                     { NULL, NULL, NULL, NULL }
                                   };

/******************************************************
 *             Static variables
 ******************************************************/

// kaizen 2013-06-26 Modified web page in order to set disable file and upgrade button
static const char send_file_page[] =
    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd\">\n"
    "<html>\n"
    "  <head>\n"
    "    <title>WizFi250 Web Server</title>\n"
    "  </head>\n"
    "  <body style=\"font-family:verdana;\">\n"
    "    <h2><span style=\"color:#ff0000\"> Wiznet</span> WizFi250 Web Server : OTA Upgrade</h2><hr>\n"
	"	 <form name=\"input\" enctype=\"multipart/form-data\" action=\"delete_app.html\" method=\"post\">"
	"      <p>Step 1 : <input type=\"submit\" value=\"Delete App\" /></p>"
	"    </form>"
    "    <form name=\"input\" enctype=\"multipart/form-data\" action=\"update.html\" method=\"post\">"
    "      <p>Step 2 : <input type=\"file\" name=\"datafile\" size=\"40\" disabled=\"disabled\"></p>"
	"      <p>Step 3 : <input type=\"submit\" value=\"Upgrade\" disabled=\"disabled\" /></p>"
    "    </form>"
    "  </body>\n"
    "</html>\n"
    "";



static const char send_update_page[] =
    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd\">\n"
    "<html>\n"
    "  <head>\n"
    "    <title>WizFi250 Web Server</title>\n"
    "  </head>\n"
    "  <body style=\"font-family:verdana;\">\n"
    "    <h2><span style=\"color:#ff0000\"> Wiznet</span> WizFi250 Web Server : OTA Upgrade</h2><hr>\n"
    "    <p>OTA Upgrade complete, device rebooting ...</p>\n"
    "  </body>\n"
    "</html>\n"
    "";

// kaizen 2013-06-26 Modified web page in order to set enable file and upgrade button after delete app
static const char send_app_delete_ok_page[] =
	    "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd\">\n"
	    "<html>\n"
	    "  <head>\n"
	    "    <title>WizFi250 Web Server</title>\n"
	    "  </head>\n"
	    "  <body style=\"font-family:verdana;\">\n"
	    "    <h2><span style=\"color:#ff0000\"> Wiznet</span> WizFi250 Web Server : OTA Upgrade</h2><hr>\n"
		"	 <form name=\"input\" enctype=\"multipart/form-data\" action=\"delete_app.html\" method=\"post\">"
		"      <p>Step 1 : <input type=\"submit\" value=\"Delete App\" disabled=\"disabled\" /></p>"
		"    </form>"
	    "    <form name=\"input\" enctype=\"multipart/form-data\" action=\"update.html\" method=\"post\">"
	    "      <p>Step 2 : <input type=\"file\" name=\"datafile\" size=\"40\"></p>"
		"      <p>Step 3 : <input type=\"submit\" value=\"Upgrade\"/></p>"
	    "    </form>"
	    "  </body>\n"
	    "</html>\n"
	    "";

/******************************************************
 *             Static Functions
 ******************************************************/



static int process_send_file( void * socket, char * params, int params_len )
{
    send_web_data( socket, (unsigned char*) send_file_page, sizeof( send_file_page ) - 1 ); /* minus one to avoid copying terminating null */
    return 0;
}

static int process_update( void * socket, char * params, int params_len )
{
    send_web_data( socket, (unsigned char*) send_update_page, sizeof( send_update_page ) - 1 ); /* minus one to avoid copying terminating null */

    return 1;
}

static int  process_del_app         ( void* socket, char * params, int params_len )
{
    platform_set_bootloader_led( 1 );
    bootloader_api->platform_erase_app( );
    platform_set_bootloader_led( 0 );

	send_web_data( socket, (unsigned char*) send_app_delete_ok_page, sizeof( send_app_delete_ok_page ) - 1 ); /* minus one to avoid copying terminating null */
	return 0;
}

void my_file_handler( void* data, int len)
{
    static uint32_t file_pos = 0;
    static uint8_t led_state = 0;
    if ( ( data == NULL ) || ( len == 0 ) )
    {
        /* End of file */

        watchdog_kick( );
        bootloader_api->platform_set_app_valid_bit( APP_VALID );
        platform_set_bootloader_led( 0 );
        file_pos = 0;
        return;
    }

//    if ( file_pos == 0 )
//    {
//        /* start of file */
//        bootloader_api->platform_set_app_valid_bit( APP_INVALID );
//        platform_set_bootloader_led( 1 );
//        bootloader_api->platform_erase_app( );
//        platform_set_bootloader_led( 0 );
//    }

    if ( led_state == 1 )
    {
        led_state = 0;
        platform_set_bootloader_led( 0 );
    }
    else
    {
        led_state = 1;
        platform_set_bootloader_led( 1 );
    }


    bootloader_api->platform_write_app_chunk( file_pos, (uint8_t*) data, len );
    file_pos += len;
}
